name: Compress Images
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Compress Images
        uses: calibreapp/image-actions@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true
          jpegQuality: '80'
          pngQuality: '80'
          webpQuality: '80'
      - name: Commit optimized images
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Compress images'
          default_author: github_actions
